okie/first/urls.py
from django.urls import path,include
from first import views

app_name='first'
urlpatterns=[
    path('register/',views.register,name='register'),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('login/',views.user_login,name='user_login'),
    
]

okie/okie/urls.py
from django.contrib import admin
from django.urls import path,include
from first import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/',include('first.urls')),
    path('', views.index, name='index')
]

okie/first/models.py
from django.db import models
from django.contrib.auth.models import User
# SuperUserInformation
# User: Jose
# Email: training@pieriandata.com
# Password: testpassword

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option="build_ext" --global-option="--disable-jpeg"
    profile_pic = models.ImageField(upload_to='first/profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

okie/first/forms.py
from django import forms
from first.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

okie/first/views.py
from django.shortcuts import render
from first.forms import UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'first/index.html')

@login_required
def special(request):
    return HttpResponse("You are Logged In , Noice")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'first/register.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
    
def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'first/login.html', {})

okie/templates/first/base.html
<!DOCTYPE html>
<html>
    <head>
    <title>
        Index
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'index' %}">Index <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'first:register' %}">REGISTER</a>
                </li>
                
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'first:logout' %}">LOGOUT</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'first:user_login' %}">LOGIN</a>
                </li>
                {% endif %}

              </ul>
            </div>
          </nav>
          <div class="container">
        
        {% block body_block %}
        {% endblock %}
    </div>
    </body>
</html>

okie/templates/first/index.html
<!DOCTYPE html>
{% extends "first/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>
        Welcome to MY SOCIAL NETWORKs
    </h1>
</div>
{% endblock %}

okie/templates/first/login.html
<!DOCTYPE html>
{% extends "first/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'first:user_login' %}" method="post">
    {% csrf_token %}
<label for="username">Username:</label>
<input type="text" name="username" placeholder="Enter Username">

<label for="password">Password</label>
<input type="password" name="password">

<input type="submit" name="" value="Login">


</form>
</div>
{% endblock %}

okie/templates/first/register.html
{% extends "first/base.html" %}


{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}